services:
  - type: web
    name: push365-casino
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DB_URL
        value: jdbc:sqlite:/app/pushdb.db?date_class=INTEGER
      - key: RECAPTCHA_ENABLED
        value: true
      - key: RECAPTCHA_SITE_KEY
        sync: false
      - key: RECAPTCHA_SITE_SECRET
        sync: false
      - key: REMEMBER_ME_KEY
        generateValue: true
      - key: APP_MAIL
        sync: false
      - key: RESEND_API_KEY
        sync: false
