services:
  - type: web
    name: push365-casino
    runtime: docker
    plan: free
    healthCheckPath: /
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DB_URL
        value: jdbc:sqlite:/data/pushdb.db
      - key: RECAPTCHA_ENABLED
        value: true
      - key: RECAPTCHA_SITE_KEY
        sync: false
      - key: RECAPTCHA_SITE_SECRET
        sync: false
      - key: REMEMBER_ME_KEY
        generateValue: true
      - key: APP_MAIL
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: MAIL_SMTP_AUTH
        value: true
      - key: MAIL_STARTTLS
        value: true
